//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ds3Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ds3Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket &quot;{0}&quot;..
        /// </summary>
        internal static string BucketDescription {
            get {
                return ResourceManager.GetString("BucketDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;BucketName&quot; parameter is not yet supported by the SDK..
        /// </summary>
        internal static string BucketNameNotImplementedException {
            get {
                return ResourceManager.GetString("BucketNameNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &quot;{0}&quot; already exists. Read-DS3Object will not merge or ovewrite directories..
        /// </summary>
        internal static string DirectoryAlreadyExistsException {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; already exists. Read-DS3Object will not overwrite the file..
        /// </summary>
        internal static string FileAlreadyExistsException {
            get {
                return ResourceManager.GetString("FileAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint &quot;{0}&quot; is not valid. Please ensure it&apos;s a proper uri with an http:// or https:// schema..
        /// </summary>
        internal static string InvalidEndpointException {
            get {
                return ResourceManager.GetString("InvalidEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhaustive switch for enum failed..
        /// </summary>
        internal static string InvalidEnumValueException {
            get {
                return ResourceManager.GetString("InvalidEnumValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is not valid. Please choose something that can be a valid filename..
        /// </summary>
        internal static string InvalidNameException {
            get {
                return ResourceManager.GetString("InvalidNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a file or directory to associate with an object key or object key prefix..
        /// </summary>
        internal static string InvalidParameterSetException {
            get {
                return ResourceManager.GetString("InvalidParameterSetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;KeyPrefix&quot; parameter is not yet supported by the SDK..
        /// </summary>
        internal static string KeyPrefixNotImplementedException {
            get {
                return ResourceManager.GetString("KeyPrefixNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file you provided did not have a proper AccessKey element..
        /// </summary>
        internal static string MissingAccessKeyException {
            get {
                return ResourceManager.GetString("MissingAccessKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the configuration was not specified..
        /// </summary>
        internal static string MissingNameException {
            get {
                return ResourceManager.GetString("MissingNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either there was no endpoint or the endpoint format was not a valid URI..
        /// </summary>
        internal static string MissingOrInvalidEndpointException {
            get {
                return ResourceManager.GetString("MissingOrInvalidEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file you provided did not have a proper SecretKey element..
        /// </summary>
        internal static string MissingSecretKeyException {
            get {
                return ResourceManager.GetString("MissingSecretKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not pull any objects because there weren&apos;t any available to pull..
        /// </summary>
        internal static string NoObjectsMessage {
            get {
                return ResourceManager.GetString("NoObjectsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no selected session..
        /// </summary>
        internal static string NoSelectedSessionException {
            get {
                return ResourceManager.GetString("NoSelectedSessionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a session named &quot;{0}&quot;..
        /// </summary>
        internal static string NoSuchSessionException {
            get {
                return ResourceManager.GetString("NoSuchSessionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object with key &quot;{0}&quot; in bucket &quot;{1}&quot;..
        /// </summary>
        internal static string ObjectDescription {
            get {
                return ResourceManager.GetString("ObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove bucket from DS3?.
        /// </summary>
        internal static string RemoveBucketConfirmationMessage {
            get {
                return ResourceManager.GetString("RemoveBucketConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove object from DS3?.
        /// </summary>
        internal static string RemoveObjectConfirmationMessage {
            get {
                return ResourceManager.GetString("RemoveObjectConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a session named &quot;{0}&quot;..
        /// </summary>
        internal static string SessionExistsException {
            get {
                return ResourceManager.GetString("SessionExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote configuration file to &quot;{0}&quot;. Use -DontPersist to prevent this behvior..
        /// </summary>
        internal static string WroteConfigFileWarning {
            get {
                return ResourceManager.GetString("WroteConfigFileWarning", resourceCulture);
            }
        }
    }
}
