var namespace_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys =
[
    [ "IChunkStrategy", "interface_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_i_chunk_strategy.html", "interface_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_i_chunk_strategy" ],
    [ "ReadRandomAccessChunkStrategy", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_read_random_access_chunk_strategy.html", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_read_random_access_chunk_strategy" ],
    [ "TransferItem", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_transfer_item.html", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_transfer_item" ],
    [ "WriteNoAllocateChunkStrategy", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_write_no_allocate_chunk_strategy.html", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_write_no_allocate_chunk_strategy" ],
    [ "WriteRandomAccessChunkStrategy", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_write_random_access_chunk_strategy.html", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_write_random_access_chunk_strategy" ],
    [ "WriteStreamChunkStrategy", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_write_stream_chunk_strategy.html", "class_ds3_1_1_helpers_1_1_strategys_1_1_chunk_strategys_1_1_write_stream_chunk_strategy" ]
];