//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ds3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ds3.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a status code of {0} when one of {1} was expected. Error message: &quot;{2}&quot;.
        /// </summary>
        internal static string BadStatusCodeException {
            get {
                return ResourceManager.GetString("BadStatusCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a status code of {0} when one of {1} was expected. Could not parse the response for additional information..
        /// </summary>
        internal static string BadStatusCodeInvalidErrorResponseException {
            get {
                return ResourceManager.GetString("BadStatusCodeInvalidErrorResponseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a seekable stream when wrapping a WindowedStream..
        /// </summary>
        internal static string CannotSeekStreamException {
            get {
                return ResourceManager.GetString("CannotSeekStreamException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered 307 number: {0}.
        /// </summary>
        internal static string Encountered307NTimes {
            get {
                return ResourceManager.GetString("Encountered307NTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the provided enumerators are not equal in length..
        /// </summary>
        internal static string EnumeratorsNotOfEqualLengthException {
            get {
                return ResourceManager.GetString("EnumeratorsNotOfEqualLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an exception when formating xml string..
        /// </summary>
        internal static string FormatXmlException {
            get {
                return ResourceManager.GetString("FormatXmlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value not accounted for in a switch statement intended to be exhaustive..
        /// </summary>
        internal static string InvalidEnumValueException {
            get {
                return ResourceManager.GetString("InvalidEnumValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SeekOrigin: {0}.
        /// </summary>
        internal static string InvalidSeekOrigin {
            get {
                return ResourceManager.GetString("InvalidSeekOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUT object streams must be both readable and seekable..
        /// </summary>
        internal static string InvalidStreamException {
            get {
                return ResourceManager.GetString("InvalidStreamException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected job type &apos;{0}&apos; but the actual job was of type &apos;{1}&apos;..
        /// </summary>
        internal static string JobRecoveryException {
            get {
                return ResourceManager.GetString("JobRecoveryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an element called &quot;{0}&quot; but didn&apos;t find it..
        /// </summary>
        internal static string MissingElementException {
            get {
                return ResourceManager.GetString("MissingElementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some or all of the objects to put are missing a size field..
        /// </summary>
        internal static string ObjectsMissingSizeException {
            get {
                return ResourceManager.GetString("ObjectsMissingSizeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many redirects..
        /// </summary>
        internal static string TooManyRedirectsException {
            get {
                return ResourceManager.GetString("TooManyRedirectsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some resources failed to dispose while handling an exception. See inner exceptions for more information..
        /// </summary>
        internal static string UsingAllException {
            get {
                return ResourceManager.GetString("UsingAllException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error while reading XML response: &quot;{0}&quot;.
        /// </summary>
        internal static string XmlResponseErrorException {
            get {
                return ResourceManager.GetString("XmlResponseErrorException", resourceCulture);
            }
        }
    }
}
